const mockMhe = [
  {
    id: 1,
    vehicleName: 'Vehicle 1',
    platNumber: 'ABC123',
    IMEINumber: '1234567890',
    simNumber: '1234567890',
    deviceType: 'Device Type 1',
    distanceCounter: 'GPS',
    speedDetection: 'FROM_DEVICE',
    timezone: 'Asia/Kolkata',
    status: true,
  },
  {
    id: 2,
    vehicleName: 'Vehicle 2',
    platNumber: 'ABC123',
    IMEINumber: '1234567890',
    simNumber: '1234567890',
    deviceType: 'Device Type 2',
    distanceCounter: 'GPS',
    speedDetection: 'FROM_DEVICE',
    timezone: 'Asia/Kolkata',
    status: true,
  },
  {
    id: 3,
    vehicleName: 'Vehicle 3',
    platNumber: 'ABC123',
    IMEINumber: '1234567890',
    simNumber: '1234567890',
    deviceType: 'Device Type 3',
    distanceCounter: 'GPS',
    speedDetection: 'FROM_DEVICE',
    timezone: 'Asia/Kolkata',
    status: true,
  },
  {
    id: 4,
    vehicleName: 'Vehicle 4',
    platNumber: 'ABC123',
    IMEINumber: '1234567890',
    simNumber: '1234567890',
    deviceType: 'Device Type 4',
    distanceCounter: 'GPS',
    speedDetection: 'FROM_DEVICE',
    timezone: 'Asia/Kolkata',
    status: true,
  },
];

export default mockMhe;
