import { IShift } from '../types/shift';

const mockShift: IShift[] = [
  {
    id: 1,
    location: 'Location 1',
    warehouseName: 'Warehouse 1',
    shiftName: 'Morning Shift',
    shiftStartTime: '08:00 AM',
    shiftEndTime: '12:00 PM',
    teaBreak: '10:00 AM',
    lunchBreak: '12:00 PM',
    setUpTime: '01:00 PM',
    bioBreak: '02:00 PM',
  },
  {
    id: 2,
    location: 'Location 2',
    warehouseName: 'Warehouse 2',
    shiftName: 'Afternoon Shift',
    shiftStartTime: '01:00 PM',
    shiftEndTime: '05:00 PM',
    teaBreak: '03:00 PM',
    lunchBreak: '05:00 PM',
    setUpTime: '06:00 PM',
    bioBreak: '07:00 PM',
  },
  {
    id: 3,
    location: 'Location 3',
    warehouseName: 'Warehouse 3',
    shiftName: 'Evening Shift',
    shiftStartTime: '06:00 PM',
    shiftEndTime: '10:00 PM',
    teaBreak: '08:00 PM',
    lunchBreak: '10:00 PM',
    setUpTime: '11:00 PM',
    bioBreak: '12:00 AM',
  },
  {
    id: 4,
    location: 'Location 4',
    warehouseName: 'Warehouse 4',
    shiftName: 'Night Shift',
    shiftStartTime: '11:00 PM',
    shiftEndTime: '03:00 AM',
    teaBreak: '01:00 AM',
    lunchBreak: '03:00 AM',
    setUpTime: '04:00 AM',
    bioBreak: '05:00 AM',
  },
  {
    id: 5,
    location: 'Location 5',
    warehouseName: 'Warehouse 5',
    shiftName: 'Midnight Shift',
    shiftStartTime: '04:00 AM',
    shiftEndTime: '08:00 AM',
    teaBreak: '06:00 AM',
    lunchBreak: '08:00 AM',
    setUpTime: '09:00 AM',
    bioBreak: '10:00 AM',
  },
];

export default mockShift;
