import { ISite } from '../types/site';

const mockSite: ISite[] = [
  {
    id: 1,
    name: 'Organization 1',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 1',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 2,
    name: 'Organization 2',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 2',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 3,
    name: 'Organization 3',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 3',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 4,
    name: 'Organization 4',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 4',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 5,
    name: 'Organization 5',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 5',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 6,
    name: 'Organization 6',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 6',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 7,
    name: 'Organization 7',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 7',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 8,
    name: 'Organization 8',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 8',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 9,
    name: 'Organization 9',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 9',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 10,
    name: 'Organization 10',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 10',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 11,
    name: 'Organization 11',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 11',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
  {
    id: 12,
    name: 'Organization 12',
    tenantId: 1,
    tenantName: 'Tenant',
    address: 'Address 12',
    contactNumber: '7896421538',
    email: 'test@organization.com',
    status: true,
  },
];

export default mockSite;
